env:
  es6: true
  node: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: 
  no-console: 0
# https://github.com/babel/babel-eslint
parser: babel-eslint  
